export const canManageAll: AbilityName = 'canManageAll'
export const canViewAdminList: AbilityName = 'canViewAdminList'
export const canViewOrganisationList: AbilityName = 'canViewOrganisationList'
export const canCreateAdmin: AbilityName = 'canCreateAdmin'
export const canDeleteAdmin: AbilityName = 'canDeleteAdmin'
export const canCreateOrganisation: AbilityName = 'canCreateOrganisation'
export const canDeleteOrganisation: AbilityName = 'canDeleteOrganisation'
